name: AntiPortals
version: '${project.version}'
main: com.tiptow.Main
api-version: '1.20'
commands:
  enableportals:
    description: Enable portal usage
    permission: portalcontrol.enable
  disableportals:
    description: Disable portal usage
    permission: portalcontrol.disable
